In [1]:
import tensorflow as tf

d:\Users\Public\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.26.1
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [2]:
sent = ['the glass of milk' , 
         ' the glass of juice' , 
        'the cup of tea ' , 
        'im a good boy' , 
        'im a good developer' , 
        'understand the meaning of words' ,
        'your videos are good']
       
       
       
       
                  

In [3]:
sent

['the glass of milk',
 ' the glass of juice',
 'the cup of tea ',
 'im a good boy',
 'im a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
### vocabulary size 

voc_size = 10000

In [7]:
from tensorflow.keras.preprocessing.text import one_hot

### one-hot encoding

In [8]:
onehot = [one_hot(words , voc_size) for words in sent ]

# here iterating through each and every words in sentence
# using one_hot and passing words and voc_size as parameter
# storing into one_hot for every word of each sentence where  ever the word is present denoted by 1 , that index we're extracting 

print(onehot)

[[9912, 3715, 5580, 7348], [9912, 3715, 5580, 5033], [9912, 2684, 5580, 480], [8314, 4989, 123, 8897], [8314, 4989, 123, 3999], [6626, 9912, 6133, 5580, 2505], [5286, 9412, 4092, 123]]


### word embedding representation

In [11]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [12]:
## pre padding 

sent_length = 8 # considering the maximum length of sentence to be  8 

embedded_docs = pad_sequences(onehot , padding = 'pre' , maxlen = sent_length)

## pad sequences will make sure that all the vectors of these words make it  8
## padding = 'pre' meaning we are adding zeros in the begining to make the size 8 
## padding ='post' meaning we are adding zeros in the last to size 8
print(embedded_docs)

[[   0    0    0    0 9912 3715 5580 7348]
 [   0    0    0    0 9912 3715 5580 5033]
 [   0    0    0    0 9912 2684 5580  480]
 [   0    0    0    0 8314 4989  123 8897]
 [   0    0    0    0 8314 4989  123 3999]
 [   0    0    0 6626 9912 6133 5580 2505]
 [   0    0    0    0 5286 9412 4092  123]]


In [14]:
dim = 10 # feature representation (dimension) size = 10

model = Sequential()

model.add(Embedding(voc_size , 10 ,input_length=sent_length ))

## embedding layer is going to work similar to word2vec this is going to train all the neural networks

model.compile('adam','mse')


In [15]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [16]:
model.predict(embedded_docs[0])

1/1 [==============================] - 1s 507ms/step


array([[-0.00545264,  0.03418095, -0.00544686,  0.00828633,  0.02628515,
        -0.00482792,  0.00257896,  0.03638475,  0.03171449,  0.0449648 ],
       [-0.00545264,  0.03418095, -0.00544686,  0.00828633,  0.02628515,
        -0.00482792,  0.00257896,  0.03638475,  0.03171449,  0.0449648 ],
       [-0.00545264,  0.03418095, -0.00544686,  0.00828633,  0.02628515,
        -0.00482792,  0.00257896,  0.03638475,  0.03171449,  0.0449648 ],
       [-0.00545264,  0.03418095, -0.00544686,  0.00828633,  0.02628515,
        -0.00482792,  0.00257896,  0.03638475,  0.03171449,  0.0449648 ],
       [ 0.04019363, -0.04122485, -0.00081321,  0.02690384,  0.04463493,
        -0.04565955,  0.04090463, -0.03296068, -0.04686643,  0.01540298],
       [ 0.02655398, -0.01681464, -0.0392651 , -0.03914296, -0.02693232,
         0.016861  ,  0.03916595,  0.02719904,  0.02543667,  0.03395337],
       [-0.04189263,  0.04584556,  0.00045569,  0.02259106,  0.01946122,
         0.03028413,  0.01413813,  0.02782449

In [17]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 238ms/step
[[[-5.45264408e-03  3.41809504e-02 -5.44686243e-03  8.28633457e-03
    2.62851454e-02 -4.82791662e-03  2.57896259e-03  3.63847502e-02
    3.17144878e-02  4.49648015e-02]
  [-5.45264408e-03  3.41809504e-02 -5.44686243e-03  8.28633457e-03
    2.62851454e-02 -4.82791662e-03  2.57896259e-03  3.63847502e-02
    3.17144878e-02  4.49648015e-02]
  [-5.45264408e-03  3.41809504e-02 -5.44686243e-03  8.28633457e-03
    2.62851454e-02 -4.82791662e-03  2.57896259e-03  3.63847502e-02
    3.17144878e-02  4.49648015e-02]
  [-5.45264408e-03  3.41809504e-02 -5.44686243e-03  8.28633457e-03
    2.62851454e-02 -4.82791662e-03  2.57896259e-03  3.63847502e-02
    3.17144878e-02  4.49648015e-02]
  [ 4.01936285e-02 -4.12248485e-02 -8.13208520e-04  2.69038416e-02
    4.46349271e-02 -4.56595533e-02  4.09046300e-02 -3.29606757e-02
   -4.68664281e-02  1.54029839e-02]
  [ 2.65539773e-02 -1.68146379e-02 -3.92650962e-02 -3.91429551e-02
   -2.69323234e-02  1.68609954